import { AudioFileItem, LineEnding, TextEncoding } from "../../types/workstation";

export interface OtoExportOptions {
  lineEnding: LineEnding;
  encoding: TextEncoding;
  includeComments: boolean;
}

export function generateOtoIniContent(files: AudioFileItem[], options: OtoExportOptions): string {
  const eol = options.lineEnding === 'CRLF' ? '\r\n' : '\n';
  const lines: string[] = [];

  if (options.includeComments) {
    lines.push(`# Generated by Unified Vocal Labeling Workstation (VLabeler Foundation)`);
    lines.push(`# Platform: Windows Native UTAU Compatibility`);
    lines.push(`# Date: ${new Date().toISOString()}`);
    lines.push(``);
  }

  for (const file of files) {
    if (!file.oto) continue;

    const alias = file.alias || file.name.replace(/\.[^/.]+$/, "");
    const offset = Math.round(file.oto.offsetMs);
    const fixed = Math.round(file.oto.fixedMs);
    const cutoff = Math.round(file.oto.cutoffMs);
    const preutterance = Math.round(file.oto.preutteranceMs);
    const overlap = Math.round(file.oto.overlapMs);

    // Standard UTAU oto.ini format:
    // filename.wav=alias,offset,fixed,cutoff,preutterance,overlap
    lines.push(`${file.name}=${alias},${offset},${fixed},${cutoff},${preutterance},${overlap}`);
  }

  return lines.join(eol) + eol;
}

/**
 * Creates a downloadable Blob with appropriate MIME type and encoding header
 */
export function createOtoIniBlob(content: string, encoding: TextEncoding): Blob {
  if (encoding === 'Shift-JIS') {
    throw new Error('Shift-JIS export requires the native desktop application.');
  }
  if (encoding === 'UTF-8-BOM') {
    // Add UTF-8 BOM bytes 0xEF, 0xBB, 0xBF
    const bom = new Uint8Array([0xEF, 0xBB, 0xBF]);
    const encoder = new TextEncoder();
    const textBytes = encoder.encode(content);
    return new Blob([bom, textBytes], { type: 'text/plain;charset=utf-8' });
  }

  return new Blob([content], { type: 'text/plain;charset=utf-8' });
}
