import { VoicebankProfile } from "../../types/workstation";

export const VOICEBANK_PROFILES: VoicebankProfile[] = [
  {
    id: 'japanese_cv',
    name: 'Japanese CV (Standard)',
    description: 'Standard Japanese consonant-vowel recording style (e.g. ka, ki, ku, ke, ko).',
    language: 'Japanese',
    recordingStyle: 'CV',
    sampleStructure: '[consonant][vowel].wav',
    defaultOverlapRatio: 0.35,
    expectedPhonemes: [
      'a', 'i', 'u', 'e', 'o',
      'ka', 'ki', 'ku', 'ke', 'ko',
      'sa', 'shi', 'su', 'se', 'so',
      'ta', 'chi', 'tsu', 'te', 'to',
      'na', 'ni', 'nu', 'ne', 'no',
      'ha', 'hi', 'fu', 'he', 'ho',
      'ma', 'mi', 'mu', 'me', 'mo',
      'ya', 'yu', 'yo',
      'ra', 'ri', 'ru', 're', 'ro',
      'wa', 'wo', 'n'
    ],
  },
  {
    id: 'japanese_vcv',
    name: 'Japanese VCV (Continuous)',
    description: 'Japanese vowel-consonant-vowel continuous recordings (e.g. - ka, a ka, i ka).',
    language: 'Japanese',
    recordingStyle: 'VCV',
    sampleStructure: '[vowel] [consonant][vowel]',
    defaultOverlapRatio: 0.45,
    expectedPhonemes: ['- a', 'a a', 'a ka', 'i ka', 'u ka', 'e ka', 'o ka'],
  },
  {
    id: 'japanese_cvvc',
    name: 'Japanese CVVC',
    description: 'Japanese consonant-vowel and vowel-consonant transitions (e.g. ka, a k).',
    language: 'Japanese',
    recordingStyle: 'CVVC',
    sampleStructure: '[consonant][vowel] and [vowel] [consonant]',
    defaultOverlapRatio: 0.30,
    expectedPhonemes: ['ka', 'ki', 'ku', 'ke', 'ko', 'a k', 'i k', 'u k', 'a s', 'i s', 'a t', 'i t'],
  },
  {
    id: 'japanese_custom',
    name: 'Japanese custom format',
    description: 'A Japanese reclist that does not follow standard CV, CVVC, or VCV. Timing defaults are generic.',
    language: 'Japanese',
    recordingStyle: 'Other',
    sampleStructure: 'Custom Japanese aliases',
    defaultOverlapRatio: 0.35,
    expectedPhonemes: [],
  },
  {
    id: 'english_arpasing',
    name: 'English ARPAsing',
    description: 'English phonetic diphones based on the CMU Arpabet dictionary (e.g. [- k], [k ae], [ae t]).',
    language: 'English',
    recordingStyle: 'ARPAsing',
    sampleStructure: '[phone1] [phone2]',
    defaultOverlapRatio: 0.33,
    expectedPhonemes: ['- k', 'k ae', 'ae t', 't -', '- s', 's ey', 'ey v'],
  },
  {
    id: 'english_custom',
    name: 'English custom format',
    description: 'A custom English reclist outside ARPAsing. No phoneme transcription is performed.',
    language: 'English',
    recordingStyle: 'Other',
    sampleStructure: 'Custom English aliases',
    defaultOverlapRatio: 0.35,
    expectedPhonemes: [],
  },
  {
    id: 'chinese_cv',
    name: 'Chinese CV',
    description: 'Consonant-vowel recordings. This profile does not perform Mandarin phoneme recognition or tone labeling.',
    language: 'Chinese',
    recordingStyle: 'CV',
    sampleStructure: '[consonant][vowel].wav',
    defaultOverlapRatio: 0.35,
    expectedPhonemes: [],
  },
  {
    id: 'chinese_vcv',
    name: 'Chinese VCV',
    description: 'Continuous vowel-consonant-vowel recordings. This profile does not perform Mandarin phoneme recognition or tone labeling.',
    language: 'Chinese',
    recordingStyle: 'VCV',
    sampleStructure: '[vowel] [consonant][vowel]',
    defaultOverlapRatio: 0.45,
    expectedPhonemes: [],
  },
  {
    id: 'chinese_cvvc',
    name: 'Chinese CVVC',
    description: 'Consonant-vowel recordings and vowel-consonant transitions. This profile does not perform Mandarin phoneme recognition or tone labeling.',
    language: 'Chinese',
    recordingStyle: 'CVVC',
    sampleStructure: '[consonant][vowel] and [vowel] [consonant]',
    defaultOverlapRatio: 0.30,
    expectedPhonemes: [],
  },
  {
    id: 'chinese_custom',
    name: 'Chinese custom format',
    description: 'A custom Chinese reclist. Timing defaults are generic; phoneme recognition and tone labeling are not performed.',
    language: 'Chinese',
    recordingStyle: 'Other',
    sampleStructure: 'Custom Chinese aliases',
    defaultOverlapRatio: 0.35,
    expectedPhonemes: [],
  },
  {
    id: 'custom',
    name: 'Other / custom format',
    description: 'Use your own filenames and aliases. No language-specific alias conversion is applied.',
    language: 'Other',
    recordingStyle: 'Other',
    sampleStructure: 'Custom',
    defaultOverlapRatio: 0.35,
    expectedPhonemes: [],
  },
];

export const JAPANESE_VOICEBANK_PROFILES = VOICEBANK_PROFILES.filter(
  profile => profile.language === 'Japanese'
);

export function getProfileById(id: string): VoicebankProfile {
  return VOICEBANK_PROFILES.find(p => p.id === id) || VOICEBANK_PROFILES[0];
}
